import Head from "next/head";
import { useGetGamesQuery } from "../store/games/games.api";

export default function Home() {
  const { data: games, isLoading, isError } = useGetGamesQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (isError) {
    return <div>Error loading games.</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Games List</h2>
        <ul>
          {games.map((game) => (
            <li key={game.id}>{game.name}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}
